# Generated by Django 3.1.2 on 2020-10-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.CharField(db_index=True, max_length=127)),
                ('developer', models.CharField(max_length=127)),
                ('dilution', models.CharField(max_length=127)),
                ('asa_iso', models.CharField(max_length=127)),
                ('a35mm', models.CharField(max_length=127)),
                ('a120', models.CharField(max_length=127)),
                ('sheet', models.CharField(max_length=127)),
                ('temp', models.CharField(max_length=127)),
                ('notes', models.CharField(max_length=127)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'The Massive Dev Chart - Film Record',
                'verbose_name_plural': 'The Massive Dev Chart - Film Record',
            },
        ),
        migrations.CreateModel(
            name='FilmRecordUpdateLocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name="locker's name")),
                ('the_first', models.BooleanField(default=True, verbose_name='is the first time to create or not')),
                ('update', models.IntegerField(default=0, verbose_name='how many times we have updated the records')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'The Massive Dev Chart - Film Record Update Locker',
                'verbose_name_plural': 'The Massive Dev Chart - Film Record Update Locker',
            },
        ),
        migrations.CreateModel(
            name='MassiveDevChartDeveloper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'The Massive Dev Chart - Developer',
                'verbose_name_plural': 'The Massive Dev Chart - Developer',
            },
        ),
        migrations.CreateModel(
            name='MassiveDevChartFilm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'The Massive Dev Chart - Film',
                'verbose_name_plural': 'The Massive Dev Chart - Film',
            },
        ),
        migrations.CreateModel(
            name='MassiveDevChartNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=127)),
                ('remark', models.CharField(max_length=255)),
                ('create_timestamp', models.DateTimeField(auto_now_add=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'The Massive Dev Chart - Note',
                'verbose_name_plural': 'The Massive Dev Chart - Note',
            },
        ),
    ]
