# Generated by Django 3.1.2 on 2020-10-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_ggfilm_backend', '0002_filmrecordupdatelocker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmrecordupdatelocker',
            name='the_first',
            field=models.BooleanField(default=True, verbose_name='is the first time to create or not'),
        ),
    ]
